### PR TITLE
Add conditional ICACHE_RAM_ATTR for interrupt handler on ESP8266

### PR DESCRIPTION
**Pull request by beikeland**

### CODE REVIEW

**Comment by ccfiel** [comment]
why is this not merge?

**Comment by ccfiel** [comment]
@beikeland still got the error even I apply your PR.

**Comment by beikeland** [comment]
> @beikeland still got the error even I apply your PR.

my guess would be your code uses other interrupt service routines that also need the same change

**Comment by ccfiel** [comment]
@beikeland If I remove the code below the error stops. 

```
  wg.begin(5, 4);
```

so i think its in the wiegand lib

**Comment by beikeland** [comment]
Then the only other possibility is that you're using the master branch of my repo instead of the branch where i applied the fix?
https://github.com/beikeland/Wiegand-Protocol-Library-for-Arduino/tree/esp-icahce

**Comment by ccfiel** [comment]
@beikeland you right :) thanks!

**Comment by frenchie71** [comment]
Ooops sorry, had not seen your pull request - I somehow requested the same ;-)

**Pull request merged**
