### PR TITLE
Update WiegandTest.ino added proper pin definitions for Leonardo 

### PR DESCRIPTION
**Pull request by Netoperz**
new IDE compatibility, and pin definitions in init, , now works on Leonardo, and also on ESP

### CODE REVIEW

**Comment by jpliew** [comment]
There is nothing wrong with the original code

In README.md

```
void setup() {
	Serial.begin(9600);  
	wg.begin(); // wg.begin(pinD0, pinD1) for ESP8266/ESP32
}
```

It is clear that user can use another declaration.

**Comment by Netoperz** [comment]
Iknow, but for dummies the example should be consistent with the wiki page, and on those graphics you clearly show pins 2 and 3 to connect to arduino, so logically the code should out of the box correspond to the manual.

That's why I think there should be declaration in example for those pins.

**Comment by jpliew** [comment]
The requirement on the README page clearly showed that

**Arduino - Any ATMEGA328 compatible board should work.**

Leonardo is not ATMEGA328.

Moreover, the graphics clearly showed it was an Arduino UNO not Aduino Leonardo.

**Comment by Netoperz** [comment]
On uno same problem. and resolved same way

**Comment by jpliew** [comment]
@Netoperz there were some changes in how Arduino uses attachInterrupt that affects the `wg.begin()`, I am already working on this. `wg.begin(2,3)` is just another way to call the init, but not the solution to the problem.

Please focus working on the WiegandNG separate issue and report back, thanks.

**Comment by Netoperz** [comment]
Ok mate :) 
I'm testing now the code you asked to test.

**Pull request closed without merging**
